# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).



## Using NumPy

Once you've installed NumPy you can import it as a library:

In [ ]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [ ]:
my_list = [1,2,3]
my_list

In [ ]:
np.array(my_list)

In [ ]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

In [ ]:
np.array(my_matrix)

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [ ]:
np.arange(0,10)

In [ ]:
np.arange(0,11,2)

### zeros and ones

Generate arrays of zeros or ones

In [ ]:
np.zeros(3)

In [ ]:
np.zeros((5,5))

In [ ]:
np.ones(3)

In [ ]:
np.ones((3,3))

### linspace
Return evenly spaced numbers over a specified interval.

In [ ]:
np.linspace(0,10,3)

In [ ]:
np.linspace(0,10,50)

## eye

Creates an identity matrix

In [ ]:
np.eye(4)

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [ ]:
np.random.rand(2)

In [ ]:
np.random.rand(5,5)

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [ ]:
np.random.randn(2)

In [ ]:
np.random.randn(5,5)

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [ ]:
np.random.randint(1,100)

In [ ]:
np.random.randint(1,100,10)

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [ ]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [ ]:
arr

In [ ]:
ranarr

## Reshape
Returns an array containing the same data with a new shape.

In [ ]:
arr.reshape(5,5)

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [ ]:
ranarr

In [ ]:
ranarr.max()

In [ ]:
ranarr.argmax()

In [ ]:
ranarr.min()

In [ ]:
ranarr.argmin()

## Shape

Shape is an attribute that arrays have (not a method):

In [ ]:
# Vector
arr.shape

In [ ]:
# Notice the two sets of brackets
arr.reshape(1,25)

In [ ]:
arr.reshape(1,25).shape

In [ ]:
arr.reshape(25,1)

In [ ]:
arr.reshape(25,1).shape

### dtype

You can also grab the data type of the object in the array:

In [ ]:
arr.dtype


### Python Matrix


In [1]:
A = [[1, 4, 5, 12], 
    [-5, 8, 9, 0],
    [-6, 7, 11, 19]]

print("A =", A) 
print("A[1] =", A[1])      # 2nd row
print("A[1][2] =", A[1][2])   # 3rd element of 2nd row
print("A[0][-1] =", A[0][-1])   # Last element of 1st Row

column = [];        # empty list
for row in A:
  column.append(row[2])   

print("3rd column =", column)

A = [[1, 4, 5, 12], [-5, 8, 9, 0], [-6, 7, 11, 19]]
A[1] = [-5, 8, 9, 0]
A[1][2] = 9
A[0][-1] = 12
3rd column = [5, 9, 11]


### NumPy Array

In [3]:
import numpy as np
a = np.array([1, 2, 3])
print(a)               # Output: [1, 2, 3]
print(type(a))         # Output: <class 'numpy.ndarray'>

[1 2 3]
<class 'numpy.ndarray'>


### How to create a NumPy array?

In [4]:
import numpy as np

A = np.array([[1, 2, 3], [3, 4, 5]])
print(A)

A = np.array([[1.1, 2, 3], [3, 4, 5]]) # Array of floats
print(A)

A = np.array([[1, 2, 3], [3, 4, 5]], dtype = complex) # Array of complex numbers
print(A)

[[1 2 3]
 [3 4 5]]
[[ 1.1  2.   3. ]
 [ 3.   4.   5. ]]
[[ 1.+0.j  2.+0.j  3.+0.j]
 [ 3.+0.j  4.+0.j  5.+0.j]]


In [9]:
import numpy as np

zeors_array = np.zeros( (2, 3) )
print(zeors_array)

[[ 0.  0.  0.]
 [ 0.  0.  0.]]


### Array of zeros and ones

In [12]:
import numpy as np
ones_array = np.ones( (1, 5), dtype=np.int32 ) #// specifying dtype
print(ones_array)      # Output: [[1 1 1 1 1]]

[[1 1 1 1 1]]


### Using arange() and shape()


In [13]:
import numpy as np

A = np.arange(4)
print('A =', A)

B = np.arange(12).reshape(2, 6)
print('B =', B)

A = [0 1 2 3]
B = [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


### Addition of Two Matrices

In [14]:
import numpy as np

A = np.array([[2, 4], [5, -6]])
B = np.array([[9, -3], [3, 6]])
C = A + B      # element wise addition
print(C)

[[11  1]
 [ 8  0]]


### Multiplication of Two Matrices

In [ ]:
 import numpy as np

A = np.array([[3, 6, 7], [5, -3, 0]])
B = np.array([[1, 1], [2, 1], [3, -3]])
C = a.dot(B)
print(C)

### Transpose of a Matrix

In [21]:
import numpy as np

A = np.array([[1, 1], [2, 1], [3, -3]])
print("Matrix \n", A)
print("Transpose \n",A.transpose())

Matrix 
 [[ 1  1]
 [ 2  1]
 [ 3 -3]]
Transpose 
 [[ 1  2  3]
 [ 1  1 -3]]


### Access matrix elements, rows and columns


In [ ]:
import numpy as np
A = np.array([2, 4, 6, 8, 10])

print("A[0] =", A[0])     # First element     
print("A[2] =", A[2])     # Third element 
print("A[-1] =", A[-1])   # Last element    

### Python Matrix


In [ ]:
import numpy as np

A = np.array([[1, 4, 5, 12],
    [-5, 8, 9, 0],
    [-6, 7, 11, 19]])

#  First element of first row
print("A[0][0] =", A[0][0])  

# Third element of second row
print("A[1][2] =", A[1][2])

# Last element of last row
print("A[-1][-1] =", A[-1][-1])     

### PAccess rows of a Matrix

In [ ]:
import numpy as np

A = np.array([[1, 4, 5, 12], 
    [-5, 8, 9, 0],
    [-6, 7, 11, 19]])

print("A[0] =", A[0]) # First Row
print("A[2] =", A[2]) # Third Row
print("A[-1] =", A[-1]) # Last Row (3rd row in this case)

In [ ]:
#Access columns of a Matrix

import numpy as np

A = np.array([[1, 4, 5, 12], 
    [-5, 8, 9, 0],
    [-6, 7, 11, 19]])

print("A[:,0] =",A[:,0]) # First Column
print("A[:,3] =", A[:,3]) # Fourth Column
print("A[:,-1] =", A[:,-1]) # Last Column (4th column in this case)